# Generated by Django 5.2.7 on 2025-10-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_venta', models.CharField(choices=[('B2B', 'Venta B2B'), ('B2C', 'Venta B2C')], max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
